apiVersion: v1
kind: Pod
metadata:
 name: helloworld
spec:
 restartPolicy: Never
 containers:
 - name: hello
   image: "wcp-docker-ci.artifactory.eng.vmware.com/vmware/photon:1.0"
   command: ["/bin/bash"]
   args:    ["-c", "while true; do echo hello, world!; sleep 1; done"]
