kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: high-performance-ssd 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
